[tox]
requires =
    tox>=4.2
env_list =
    clean
    pre-commit
    py3{10-13}-{amgi-aiobotocore, amgi-aiokafka, amgi-common, amgi-paho-mqtt, amgi-redis, amgi-sqs-event-source-mapping, amgi-types, asyncfast}

[testenv]
runner = uv-venv-lock-runner
description = run the tests with pytest
pass_env =
    DOCKER_HOST
    RYUK_CONTAINER_IMAGE
    RYUK_RECONNECTION_TIMEOUT
    TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE
    TESTCONTAINERS_RYUK_DISABLED
    TESTCONTAINERS_RYUK_PRIVILEGED
commands =
    pytest {tty:--color=yes} {posargs:-v --cov --cov-append --cov-report=xml}

[testenv:clean]
runner = uv-venv-lock-runner
description = clean coverage report
commands =
    coverage erase
uv_sync_flags = --all-packages

[testenv:pre-commit]
runner = uv-venv-lock-runner
description = run pre-commit
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:py3{10-13}-amgi-aiobotocore]
commands =
    {[testenv]commands} packages/amgi-aiobotocore
depends =
    clean
uv_sync_flags = --package=amgi-aiobotocore

[testenv:py3{10-13}-amgi-aiokafka]
commands =
    {[testenv]commands} packages/amgi-aiokafka
depends =
    clean
uv_sync_flags = --package=amgi-aiokafka

[testenv:py3{10-13}-amgi-common]
commands =
    {[testenv]commands} packages/amgi-common
depends =
    clean
uv_sync_flags = --package=amgi-common

[testenv:py3{10-13}-amgi-paho-mqtt]
commands =
    {[testenv]commands} packages/amgi-paho-mqtt
depends =
    clean
uv_sync_flags = --package=amgi-paho-mqtt

[testenv:py3{10-13}-amgi-redis]
commands =
    {[testenv]commands} packages/amgi-redis
depends =
    clean
uv_sync_flags = --package=amgi-redis

[testenv:py3{10-13}-amgi-sqs-event-source-mapping]
commands =
    {[testenv]commands} packages/amgi-sqs-event-source-mapping
depends =
    clean
uv_sync_flags = --package=amgi-sqs-event-source-mapping

[testenv:py3{10-13}-amgi-types]
commands =
    {[testenv]commands} packages/amgi-types
depends =
    clean
uv_sync_flags = --package=amgi-types

[testenv:py3{10-13}-asyncfast]
commands =
    {[testenv]commands} packages/asyncfast
depends =
    clean
uv_sync_flags = --package=asyncfast
